site_name: pytry docs

site_description: 'pytry documentations'

site_author: 'Shabbir Mousavi'

docs_dir: docs/

repo_name: 'sshmo/pytry'

repo_url: 'https://github.com/sshmo/pytry'

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - pytry docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
