site_name: djtry

site_description: 'djtry documentations'

site_author: 'Shabbir Mousavi'

docs_dir: docs/

repo_name: 'sshmo/djtry'

repo_url: 'https://github.com/sshmo/djtry'

theme:
  name: "material"

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav
  - section-index
  - mkdocstrings

nav:
  - Home: index.md
  - Usage: tutorials.md
  - djtry: reference/
