[tool.black]
line-length = 120
target_version = ['py38',]

[tool.isort]
profile = "black"

[tool.bandit]
exclude_dirs = ["tests",]
include_dirs = ["djtry",]

[tool.pylint.format]
max-line-length=120

[tool.pylint.messages_control]
# disable=["C","R","W",]

[tool.pylint.design]
max-parents=13

[tool.pylint.typecheck]
ignored-modules=["tests",]

[tool.pylint.main]
django-settings-module="djtry.settings"
ignore-patterns="tests"

[tool.pytest.ini_options]
testpaths=["tests",]
addopts = "--cov --cov-report term-missing"
DJANGO_SETTINGS_MODULE = "djtry.settings"


[tool.coverage.run]
omit = ["*/migrations/*", "*/tests/*", "*/venv/*"]

[tool.ruff]
line-length = 120

[tool.flake8]
ignore = ['E203', 'W503']
max-line-length = 120

[tool.pytype]
# Space-separated list of files or directories to process.
inputs = ['pytry']
# Comma or space separated list of error names to ignore.
# disable = ['pyi-error', 'import-error']
